### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by charlesmcelhannon** [m-byte918/MultiOgarII#1527]
> G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\modules\Vec2.js:34
            throw new TypeError(`Tried to do math with ${vecOrNum}.`);
            ^

TypeError: Tried to do math with NaN.
    at Vec2.executeOperation (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\modules\Vec2.js:34:19)
    at Vec2.multiply (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\modules\Vec2.js:52:14)
    at Vec2.product (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\modules\Vec2.js:56:29)
    at Server.ejectMass (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\Server.js:797:43)
    at PlayerTracker.pressW (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\PlayerTracker.js:347:21)
    at PacketHandler.process (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\PacketHandler.js:220:39)
    at PlayerTracker.updateTick (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\PlayerTracker.js:191:35)
    at Server.updateClients (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\Server.js:312:43)
    at Server.mainLoop (G:\Downloads\MultiOgarII-master\MultiOgarII-master\src\Server.js:512:14)
    at listOnTimeout (internal/timers.js:531:17)

The server always crashes a few minutes after I start it with this error.

**Comment by LegitEzra** [comment]
what version of node do you have?

**Comment by charlesmcelhannon** [comment]
lastest release. Switching to linux is a temporary solution as that is working perfectly fine.

**Comment by charlesmcelhannon** [comment]
latest release=13.1.0

**Comment by charlesmcelhannon** [comment]
I was also wondering how to allowcate more memory as the amount is just a mere 14.5 megabytes.

**Comment by agarian-2** [comment]
Either the cell size or cell position became NaN, from what I see.
https://github.com/m-byte918/MultiOgarII/blob/master/src/Server.js#L797

**Comment by Tombez** [comment]
If the problem comes up again, please reopen this issue.
