### ISSUE TITLE
Experimental mode is broken

### ISSUE THREAD

**Issue by wolfy01** [m-byte918/MultiOgarII#1534]
When a mother cell eats a player, it causes this error:
```
C:\Users\wolfy.DESKTOP-0QI782C\Downloads\Agar.io\MultiOgarII-master\MultiOgarII-master\src\entity\MotherCell.js:49
            const pos = this.position.sum(Vec2.fromAngle(angle).multiply(size1));
                                          ^

ReferenceError: Vec2 is not defined
    at MotherCell.onUpdate (C:\Users\wolfy.DESKTOP-0QI782C\Downloads\Agar.io\MultiOgarII-master\MultiOgarII-master\s
rc\entity\MotherCell.js:49:43)
    at Experimental.onTick (C:\Users\wolfy.DESKTOP-0QI782C\Downloads\Agar.io\MultiOgarII-master\MultiOgarII-master\s
rc\gamemodes\Experimental.js:59:28)
    at Server.mainLoop (C:\Users\wolfy.DESKTOP-0QI782C\Downloads\Agar.io\MultiOgarII-master\MultiOgarII-master\src\S
erver.js:507:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by wolfy01** [comment]
Fixed by adding 
```js
const Vec2 = require('../modules/Vec2')
``` to MotherCell.js

**Comment by Tombez** [comment]
If you experience the bug again, please reopen this issue.
