### ISSUE TITLE
Can't start the server.

### ISSUE THREAD

**Issue by stuprapolli** [m-byte918/MultiOgarII#1543]
After I've downloaded the server (and Node) and followed the steps, at the command "node index.js" a syntax error is shown up:
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\PC\Desktop\MultiOgarII-master\node_modules\ws\index.js:3:19)

I don't have a clue of what that means; I would appreciate some help as soon as possible.
Thanks in advance.

**Comment by Tombez** [comment]
Seems like you have a version of node that doesn't recognize the ellipsis operator `...`
You should be able to check what version of node is running with `node --version`.
You can try uninstalling node and reinstalling the latest stable version.
If that isn't the issue, let me know.

**Comment by stuprapolli** [comment]
It works now! Thank you for your time.
