### ISSUE TITLE
update to the new uwebsocket [bug]

### ISSUE THREAD

**Issue by ItsDavehere** [m-byte918/MultiOgarII#1553]
uws is deprecated
this happens when config is uws

********************************** output ************************************
` this.wsServer = new this.WebSocket.Server(wsOptions);
                        ^

TypeError: this.WebSocket.Server is not a constructor
    at Server.start (/Users/hama/Downloads/ogarii/src/Server.js:89:25)
    at Object.<anonymous> (/Users/hama/Downloads/ogarii/src/index.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

**Comment by Tombez** [comment]
That error is for OgarII. Follow the directions in the README https://github.com/Luka967/OgarII

**Comment by Borys64** [comment]
Ironically it doesn't seem to be, I don't think OgarII creates an instance of a server that way. I've just tested using the module and a similar error appears. :man_shrugging: 
@ItsDavehere Are you sure this is MultiOgarII?
I'll re-open till I remove the faulty feature.

**Comment by Borys64** [comment]
Also, `uws` seems to indeed be deprecated, its unnecessary to switch between modules when `ws` is sufficient.

**Comment by ItsDavehere** [comment]
@Borys64 yes you can test it and see
