### ISSUE TITLE
SyntaxError: Unexpected token . (outdated Node.js)

### ISSUE THREAD

**Issue by biomseed** [m-byte918/MultiOgarII#1556]
When I run the thing it says this:
        if (this.spectateTarget?.isRemoved) this.spectateTarget = null;
                                ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (my downloads\MultiOgarII-master\MultiOgarII-master\src\Server.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by Tombez** [comment]
What version of node are you using? Have you tried making sure it's up to date?

**Comment by biomseed** [comment]
> What version of node are you using? Have you tried making sure it's up to date?

let me check

**Comment by biomseed** [comment]
v10.16.0

**Comment by Tombez** [comment]
Yeah I'm on v15.3.0 and it's working fine for me. Try updating node.

**Comment by biomseed** [comment]
k

**Comment by biomseed** [comment]
thanks it works

**Comment by biomseed** [comment]
but also agario might have removed the way to connect to servers with ip adresses

**Comment by Tombez** [comment]
Yeah, currently this server doesn't work with the official client.
